name: Build & Push Podman Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Podman
        run: sudo apt update && sudo apt install -y podman

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | podman login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io

      - name: Build & Push Image
        run: |
          podman build -t docker.io/pradeepkuduukil/podman-app:latest .
          podman push docker.io/pradeepkuduukil/podman-app:latest
